### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#26]

**Comment by JoshCheek** [comment]
I guess I'd look for reasons that the denominator is zero. Usually, IME, it comes from doing something across a collection, eg:

```ruby
students = []
sum      = students.inject(0) { |sum, student| sum + student.grade }
average  = sum / students.size # ~> ZeroDivisionError: divided by 0

# ~> ZeroDivisionError
# ~> divided by 0
# ~>
# ~> /var/folders/7g/mbft22555w3_2nqs_h1kbglw0000gn/T/seeing_is_believing_temp_dir20150330-70072-1xq3e4r/program.rb:3:in `/'
# ~> /var/folders/7g/mbft22555w3_2nqs_h1kbglw0000gn/T/seeing_is_believing_temp_dir20150330-70072-1xq3e4r/program.rb:3:in `<main>'
```
