### ISSUE TITLE
exit within spec raises error

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#57]
It sends the SystemExit to the heuristic

```ruby
ArgumentError | Asked for a heuristic on an object we don't accept: #<ErrorToCommunicate::ExceptionInfo:0x007f95408498b0 @exception=#<SystemExit: exit>, @classname="SystemExit", @message="exit", @backtrace=[#<ExInfo::Loc ./spec/features/today_spec.rb:44:in `exit' pred:true succ:false>, #<ExInfo::Loc ./spec/features/today_spec.rb:44:in `block (3 levels) in <top (required)>' pred:true succ:true>, #<ExInfo::Loc ./spec/features/today_spec.rb:41:in `each' pred:true succ:true>, #<ExInfo::Loc ./spec/features/today_spec.rb:41:in `block (2 levels) in <top (required)>' pred:false succ:true>]>
======================================================================
../../../.gem/ruby/2.2.2/gems/what_weve_got_here_is_an_error_to_communicate-0.0.6/lib/error_to_communicate/config.rb:60
   55:       einfo = ExceptionInfo.parse(exception)
   56:       !blacklist.call(einfo) && !!heuristics.find { |h| h.for? einfo }
   57:     end
   58:
   59:     def heuristic_for(exception)
-> 60:       accept?(exception) || raise(ArgumentError, "Asked for a heuristic on an object we don't accept: #{exception.inspect}")
   61:       einfo = ExceptionInfo.parse(exception)
   62:       heuristics.find { |heuristic| heuristic.for? einfo }
   63:                 .new(einfo: einfo, project: project)
   64:     end
```

**Comment by JoshCheek** [comment]
Doesn't seem to be true anymore.
